_homepage:
    pattern: /
    defaults: { _controller: WebappBlackspanBundle:Default:index }
WebappBlackspanBundle_blackspan:
    resource: "@WebappBlackspanBundle/Resources/config/routing/request.yml"
    prefix:   /blackspan
    