_homepage:
    pattern: /
    defaults: { _controller: WebappBlackspanBundle:Default:index }

WebappBlackspanBundle:
    resource: "@WebappBlackspanBundle/Resources/config/routing.yml"
    prefix:   /blackspan
